### PR TITLE
Add dependabot to update dependencies

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Review by bdemers — APPROVED** [review]
❤️

**Comment by bdemers** [comment]
This build error _should_ be resolved by: https://github.com/okta/okta-cli/pull/87
(edited through the GitHub UI, so don't hold me to it)

**Comment by mraible** [comment]
@bdemers When I tried the following command:

```
choco install visualstudio2017-workload-vctools --package-parameters "--no-includeRecommended"
```

The error is:

```
visualstudio2017-workload-vctools v1.3.2 [Approved]
visualstudio2017-workload-vctools package files install completed. Performing other installation steps.
ERROR: Unable to detect any supported Visual Studio product. You may try passing --installPath or both --productId and --channelId parameters.
The install of visualstudio2017-workload-vctools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-vctools\tools\ChocolateyInstall.ps1'.
 See log for details.
```

It almost looks like you need a license for Visual Studio.

**Comment by mraible** [comment]
Please merge when you get a chance.

**Pull request merged**
